FROM php:8.2-cli

RUN apt-get update && apt-get install -y libpq-dev vim \
    && docker-php-ext-install pdo pdo_pgsql

RUN apt-get install -y php-dev autoconf automake
RUN pecl install xdebug-3.2.2
RUN docker-php-ext-enable xdebug
RUN echo "zend_extension=xdebug" >> /usr/local/etc/php/conf.d/99-xdebug.ini

WORKDIR /var/www/html

EXPOSE 80

CMD ["php", "-S", "0.0.0.0:80", "-t", "/var/www/html"]
